[parity]
mode = "last"
chain = "Testchain"
base_path = "../testchain/parity"
db_path = "../testchain/parity/chains"
keys_path = "../testchain/keystore"
identity = "Testchain Node"
light = false

[rpc]
disable = false
port = 8646
interface = "all"
cors = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc"]
hosts = ["all"]

[websockets]
disable = false
port = 8647
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc"]
hosts = ["none"]

[ui]
disable = true

[ipc]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false

[snapshots]
disable_periodic = true

[misc]
logging = "own_tx=trace"
log_file = "../testchain/parity/testchain.log"
color = true
